language: c

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - cmake-data
            - gcc-6
            - g++-6

    - os: osx
      osx_image: xcode8.2
      compiler: clang
      before_install:
        - brew upgrade
        - brew install cmake

script:
  - if [ "$CC" = "gcc" ]; then export CC="gcc-6" CXX="g++-6"; fi
  - mkdir build
  - cd build
  - cmake ..
  - make
