language: c

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - cmake-data
            - gcc-6
            - g++-6
      env:
        - ARTIFACT_NAME=redream.x86_64-linux.tar.gz

    - os: osx
      osx_image: xcode8.2
      compiler: clang
      env:
        - ARTIFACT_NAME=redream.x86_64-darwin.tar.gz
      before_install:
        - brew upgrade
        - brew install cmake

script:
  - if [ "$CC" = "gcc" ]; then export CC="gcc-6" CXX="g++-6"; fi
  - mkdir build
  - cd build
  - cmake ..
  - make

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && .
  - tar -cvzf $ARTIFACT_NAME ../profiles redream
  - export SSHPASS=$DEPLOY_PASS
  - sshpass -e scp $ARTIFACT_NAME $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
